version: '3' # composeファイルのバーション指定
services:
  app: # service名
    build: ./go # ビルドに使用するDockerfileがあるディレクトリ指定
    tty: true # コンテナの起動永続化
    volumes:
      - $PWD/../src:/go/src # マウントディレクトリ指定
    environment:
      - "GOPATH=/go"
    networks:
      elasticsearch:
        ipv4_address: 172.54.0.2

  php:
    build: ./php
    tty: true
    volumes:
      - $PWD/../src:/var/www/php
    networks:
      elasticsearch:
        ipv4_address: 172.54.0.3

  elasticsearch:
    build: ./elasticsearch
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      - cluster.name=laradock-cluster
      - node.name=laradock-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.initial_master_nodes=laradock-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      elasticsearch:
        ipv4_address: 172.54.0.54

  kibana:
    build: ./kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      elasticsearch:
        ipv4_address: 172.54.0.55

volumes:
  elasticsearch:
    driver: local

networks:
  elasticsearch:
    ipam:
      config:
        - subnet: 172.54.0.0/24
